### ISSUE TITLE
Idea: use a thread pool

### ISSUE THREAD

**Issue by naparuba** [shinken-monitoring/mod-native-plugins#1]
By default the woker will launch 1 check in // and there will be N proc workers, so won't do lot of // executions. With network time we can only use few cpu when we can spawn others checks ^^

So I think we should set a thread pool that will get job and launch checks.

**Comment by gst** [comment]
yeaaah that's the thing to do here, I had already the idea before/from the start ;)
will come in my next job session on it :p

**Comment by naparuba** [comment]
^^

**Comment by gst** [comment]
Done / Implemented.

Actually it's a static pool (fixed number of threads, default to 4). 

Though you can change that number of threads by using 'worker_threads = xx'  in the module configuration.
